// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The provider-gitlab Authors
// This code has been partially generated by an AI.

// Package plugin provides a subprocess SemRel plugin that creates GitLab releases.
package plugin

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"
)

const (
	defaultBaseURL = "https://gitlab.com"
	defaultTimeout = 30 * time.Second
)

// Config contains the GitLab release settings sourced from the SemRel environment.
type Config struct {
	BaseURL          string
	AuthHeader       string
	Token            string
	ProjectID        string
	TagName          string
	Name             string
	Description      string
	Branch           string
	CommentOnMRs     bool
	CommitHashes     []string
	ProjectURL       string
	commentConfigErr error
	HTTPClient       *http.Client
}

// Release represents the subset of the GitLab release response used by the plugin.
type Release struct {
	TagName     string `json:"tag_name"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// Creator creates GitLab releases.
type Creator struct {
	baseURL     string
	authHeader  string
	token       string
	projectID   string
	tagName     string
	name        string
	description string
	branch      string
	projectURL  string
	httpClient  *http.Client
}

type createReleaseRequest struct {
	TagName     string `json:"tag_name"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Ref         string `json:"ref,omitempty"`
}

// ConfigFromEnv loads plugin configuration from the SemRel subprocess environment.
func ConfigFromEnv() Config {
	return ConfigFromLookupEnv(os.LookupEnv)
}

// ConfigFromLookupEnv loads plugin configuration from the provided environment lookup.
func ConfigFromLookupEnv(lookupEnv func(string) (string, bool)) Config {
	baseURL := strings.TrimSpace(envValue(lookupEnv, "SEMREL_PLUGIN_BASE_URL"))
	if baseURL == "" {
		baseURL = defaultBaseURL
	}

	projectID := strings.TrimSpace(envValue(lookupEnv, "SEMREL_PLUGIN_PROJECT_ID"))
	if projectID == "" {
		projectID = strings.TrimSpace(envValue(lookupEnv, "CI_PROJECT_ID"))
	}

	tagName := strings.TrimSpace(envValue(lookupEnv, "SEMREL_TAG_NAME"))
	authHeaderName, authHeaderValue := authHeader(lookupEnv)
	commentOnMRs, commentErr := parsePluginBool(envValue(lookupEnv, "SEMREL_PLUGIN_COMMENT_ON_MRS"))

	cfg := Config{
		BaseURL:      baseURL,
		AuthHeader:   authHeaderName,
		Token:        authHeaderValue,
		ProjectID:    projectID,
		TagName:      tagName,
		Name:         tagName,
		Description:  envValue(lookupEnv, "SEMREL_CHANGELOG"),
		Branch:       strings.TrimSpace(envValue(lookupEnv, "SEMREL_BRANCH")),
		CommentOnMRs: commentOnMRs != nil && *commentOnMRs,
		ProjectURL:   strings.TrimRight(strings.TrimSpace(envValue(lookupEnv, "CI_PROJECT_URL")), "/"),
	}
	if commentErr != nil {
		cfg.commentConfigErr = fmt.Errorf("SEMREL_PLUGIN_COMMENT_ON_MRS: %w", commentErr)
	}
	if cfg.CommentOnMRs {
		cfg.CommitHashes, cfg.commentConfigErr = parseCommitHashes(envValue(lookupEnv, "SEMREL_COMMIT_HASHES"))
	}
	return cfg
}

// Validate reports missing or malformed configuration.
func (c Config) Validate() error {
	if c.commentConfigErr != nil {
		return c.commentConfigErr
	}
	if strings.TrimSpace(c.Token) == "" {
		return errors.New("SEMREL_PLUGIN_TOKEN, SEMREL_PLUGIN_JOB_TOKEN, or CI_JOB_TOKEN is required")
	}
	if strings.TrimSpace(c.ProjectID) == "" {
		return errors.New("SEMREL_PLUGIN_PROJECT_ID or CI_PROJECT_ID is required")
	}
	if strings.TrimSpace(c.TagName) == "" {
		return errors.New("SEMREL_TAG_NAME is required")
	}
	if strings.TrimSpace(c.Name) == "" {
		return errors.New("release name is required")
	}

	parsedURL, err := url.Parse(strings.TrimSpace(c.BaseURL))
	if err != nil || parsedURL.Scheme == "" || parsedURL.Host == "" {
		return fmt.Errorf("SEMREL_PLUGIN_BASE_URL must be a valid absolute URL")
	}

	return nil
}

// New returns a GitLab release creator.
func New(cfg Config) *Creator {
	baseURL := strings.TrimRight(strings.TrimSpace(cfg.BaseURL), "/")
	if baseURL == "" {
		baseURL = defaultBaseURL
	}
	authHeaderName := strings.TrimSpace(cfg.AuthHeader)
	if authHeaderName == "" && strings.TrimSpace(cfg.Token) != "" {
		authHeaderName = "PRIVATE-TOKEN"
	}

	httpClient := cfg.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{Timeout: defaultTimeout}
	}

	return &Creator{
		baseURL:     baseURL,
		authHeader:  authHeaderName,
		token:       strings.TrimSpace(cfg.Token),
		projectID:   url.PathEscape(strings.TrimSpace(cfg.ProjectID)),
		tagName:     strings.TrimSpace(cfg.TagName),
		name:        strings.TrimSpace(cfg.Name),
		description: cfg.Description,
		branch:      strings.TrimSpace(cfg.Branch),
		projectURL:  strings.TrimRight(strings.TrimSpace(cfg.ProjectURL), "/"),
		httpClient:  httpClient,
	}
}

// CreateRelease creates a GitLab release from the current SemRel context.
func (c *Creator) CreateRelease(ctx context.Context) (*Release, error) {
	payload := createReleaseRequest{
		TagName:     c.tagName,
		Name:        c.name,
		Description: c.description,
		Ref:         c.branch,
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("gitlab: marshal release request: %w", err)
	}

	endpoint := fmt.Sprintf("%s/api/v4/projects/%s/releases", c.baseURL, c.projectID)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("gitlab: create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set(c.authHeader, c.token)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("gitlab: create release: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusCreated {
		responseBody, _ := io.ReadAll(io.LimitReader(resp.Body, 1024))
		return nil, fmt.Errorf("gitlab: create release: status %d: %s", resp.StatusCode, strings.TrimSpace(string(responseBody)))
	}

	var release Release
	if err := json.NewDecoder(resp.Body).Decode(&release); err != nil {
		return nil, fmt.Errorf("gitlab: decode release response: %w", err)
	}

	return &release, nil
}

// CommentOnMergeRequests comments on merge requests containing release commits.
func (c *Creator) CommentOnMergeRequests(ctx context.Context, cfg Config, _ *Release) error {
	if !cfg.CommentOnMRs || len(cfg.CommitHashes) == 0 {
		return nil
	}
	pullRequests := make(map[int64]struct{})
	for _, hash := range cfg.CommitHashes {
		endpoint := fmt.Sprintf("%s/api/v4/projects/%s/repository/commits/%s/merge_requests",
			c.baseURL, c.projectID, url.PathEscape(strings.TrimSpace(hash)))
		var associated []struct {
			IID int64 `json:"iid"`
		}
		if err := c.requestJSON(ctx, http.MethodGet, endpoint, nil, &associated); err != nil {
			return fmt.Errorf("gitlab: list merge requests for commit %s: %w", hash, err)
		}
		for _, mr := range associated {
			if mr.IID > 0 {
				pullRequests[mr.IID] = struct{}{}
			}
		}
	}

	marker := "<!-- semrel-release:" + cfg.TagName + " -->"
	message := fmt.Sprintf("%s\nThis merge request has been included in release `%s`.", marker, cfg.TagName)
	if c.projectURL != "" {
		message = fmt.Sprintf("%s\nThis merge request has been included in release [%s](%s/-/releases/%s).",
			marker, cfg.TagName, c.projectURL, url.PathEscape(cfg.TagName))
	}
	for iid := range pullRequests {
		notesURL := fmt.Sprintf("%s/api/v4/projects/%s/merge_requests/%d/notes?per_page=100",
			c.baseURL, c.projectID, iid)
		var notes []struct {
			Body string `json:"body"`
		}
		if err := c.requestJSON(ctx, http.MethodGet, notesURL, nil, &notes); err != nil {
			return fmt.Errorf("gitlab: list notes for merge request !%d: %w", iid, err)
		}
		alreadyCommented := false
		for _, note := range notes {
			if strings.Contains(note.Body, marker) {
				alreadyCommented = true
				break
			}
		}
		if alreadyCommented {
			continue
		}
		body, err := json.Marshal(struct {
			Body string `json:"body"`
		}{Body: message})
		if err != nil {
			return fmt.Errorf("gitlab: marshal release note for merge request !%d: %w", iid, err)
		}
		if err := c.requestJSON(ctx, http.MethodPost,
			fmt.Sprintf("%s/api/v4/projects/%s/merge_requests/%d/notes", c.baseURL, c.projectID, iid),
			bytes.NewReader(body), nil); err != nil {
			return fmt.Errorf("gitlab: post release note to merge request !%d: %w", iid, err)
		}
	}
	return nil
}

func (c *Creator) requestJSON(ctx context.Context, method, endpoint string, body io.Reader, result any) error {
	req, err := http.NewRequestWithContext(ctx, method, endpoint, body)
	if err != nil {
		return fmt.Errorf("build request: %w", err)
	}
	req.Header.Set(c.authHeader, c.token)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("send request: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		responseBody, readErr := io.ReadAll(io.LimitReader(resp.Body, 1024))
		if readErr != nil {
			return fmt.Errorf("unexpected status %s (reading body: %v)", resp.Status, readErr)
		}
		return fmt.Errorf("unexpected status %s: %s", resp.Status, strings.TrimSpace(string(responseBody)))
	}
	if result != nil {
		if err := json.NewDecoder(resp.Body).Decode(result); err != nil {
			return fmt.Errorf("decode response: %w", err)
		}
	}
	return nil
}

func parseCommitHashes(raw string) ([]string, error) {
	var hashes []string
	if strings.TrimSpace(raw) == "" {
		return nil, nil
	}
	if err := json.Unmarshal([]byte(raw), &hashes); err != nil {
		return nil, fmt.Errorf("SEMREL_COMMIT_HASHES must be a JSON array: %w", err)
	}
	return hashes, nil
}

func envValue(lookupEnv func(string) (string, bool), key string) string {
	value, ok := lookupEnv(key)
	if !ok {
		return ""
	}
	return value
}

func authHeader(lookupEnv func(string) (string, bool)) (name, value string) {
	if token := strings.TrimSpace(envValue(lookupEnv, "SEMREL_PLUGIN_TOKEN")); token != "" {
		return "PRIVATE-TOKEN", token
	}
	if token := strings.TrimSpace(envValue(lookupEnv, "SEMREL_PLUGIN_JOB_TOKEN")); token != "" {
		return "JOB-TOKEN", token
	}
	if envBool(lookupEnv, "SEMREL_PLUGIN_USE_JOB_TOKEN") {
		if token := strings.TrimSpace(envValue(lookupEnv, "CI_JOB_TOKEN")); token != "" {
			return "JOB-TOKEN", token
		}
		return "", ""
	}
	if token := strings.TrimSpace(envValue(lookupEnv, "CI_JOB_TOKEN")); token != "" {
		return "JOB-TOKEN", token
	}
	return "", ""
}

func envBool(lookupEnv func(string) (string, bool), key string) bool {
	return strings.EqualFold(strings.TrimSpace(envValue(lookupEnv, key)), "true")
}

func parsePluginBool(raw string) (*bool, error) {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "":
		return nil, nil
	case "1", "true", "yes", "on":
		value := true
		return &value, nil
	case "0", "false", "no", "off":
		value := false
		return &value, nil
	default:
		return nil, fmt.Errorf("must be a boolean")
	}
}
